kind: pipeline
name: deploy
type: docker
concurrency:
  limit: 1
steps:
  - name: slack-begin
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      username: Drone
      icon_url: ${DRONE_COMMIT_AUTHOR_AVATAR}
      template: >
        {{repo.name}}/{{build.branch}} - Started #{{build.number}} "${DRONE_COMMIT_MESSAGE}" by ${DRONE_COMMIT_AUTHOR} (${DRONE_COMMIT_AUTHOR_EMAIL}) (<{{build.link}}|Open>)
  - name: deploy
    image: devforth/drone-builder
    commands:
      - cd deploy && /bin/bash build.sh
  - name: slack-end
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      username: Drone
      icon_url: ${DRONE_COMMIT_AUTHOR_AVATAR}
      template: >
        {{repo.name}}/{{build.branch}} - #{{build.number}} {{uppercasefirst build.status}} after {{since build.started}} (<{{build.link}}|Open>)
