version: '3'

services:

  app:
    build: ./print_api_server
    restart: "always"
    env_file:
      - ./print_api_server/.env
    ports:
      - "5000:5000"
    volumes:
      - ".:/print_api_server/"
    command: bash -c "python ./print_api_server/app.py"
  db:
    image: postgres:latest
    restart: always
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  postgres: null
