version: '3'

services:

  app:
    build: ./src
    restart: "always"
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ".:/src/"
    command: bash -c "python ./src/app.py"
  db:
    image: postgres:latest
    restart: always
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  postgres: null
